sudo: false

language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1

install:
  - composer install
  - composer global require phpspec/phpspec
  - export PATH=$PATH:$HOME/.composer/vendor/bin/

script:
  - phpspec run --verbose
