sudo: false

language: php

php:
  - 7.4

install:
  - composer install
  - wget -O phive.phar https://phar.io/releases/phive.phar
  - php phive.phar install phpspec/phpspec:6 --force-accept-unsigned

script:
  - tools/phpspec run --verbose
